export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_RECEIVE = 'PRODUCT_RECEIVE';

export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE';

export const MORE_PRODUCTS_REQUEST = 'MORE_PRODUCTS_REQUEST';
export const MORE_PRODUCTS_RECEIVE = 'MORE_PRODUCTS_RECEIVE';

export const PAGE_REQUEST = 'PAGE_REQUEST';
export const PAGE_RECEIVE = 'PAGE_RECEIVE';

export const CART_REQUEST = 'CART_REQUEST';
export const CART_RECEIVE = 'CART_RECEIVE';

export const CART_ITEM_ADD_REQUEST = 'CART_ITEM_ADD_REQUEST';

export const CART_ITEM_DELETE_REQUEST = 'CART_ITEM_DELETE_REQUEST';

export const CART_ITEM_UPDATE_REQUEST = 'CART_ITEM_UPDATE_REQUEST';

export const SHIPPING_METHODS_REQUEST = 'SHIPPING_METHODS_REQUEST';
export const SHIPPING_METHODS_RECEIVE = 'SHIPPING_METHODS_RECEIVE';

export const PAYMENT_METHODS_REQUEST = 'PAYMENT_METHODS_REQUEST';
export const PAYMENT_METHODS_RECEIVE = 'PAYMENT_METHODS_RECEIVE';

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_RECEIVE = 'CHECKOUT_RECEIVE';

export const SITEMAP_REQUEST = 'SITEMAP_REQUEST';
export const SITEMAP_RECEIVE = 'SITEMAP_RECEIVE';

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_PRODUCTS_FILTER = 'SET_PRODUCTS_FILTER';

export const LOCATION_CHANGED = 'LOCATION_CHANGED';
